### ISSUE TITLE
Disabling async is broken

### ISSUE THREAD

**Issue by matze** [ufo-kit/concert#301]
Running `runtests.py --disable-async` breaks many tests when calling the wrapped function.

**Comment by tfarago** [comment]
We need the traceback print because when something doesn't work with futures the first thing I do is to disable them and I want to see where the exception originates.
We can make a switch in `concert.config` or something, I will come up with a PR.

**Comment by matze** [comment]
Alright!

**Comment by tfarago** [comment]
This was never a bug concerned with the printing itself but actually caused by loosing the `traceback` module in the history...
