### ISSUE TITLE
Adding a callback to the @async future that prints an exception

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/concert#355]
I had a few times problems that I havend noticed a exception of an asynchronous function, i.e. when 'device.motor.move' violates a limit.

I had the idea to add a function to every async as a callback that prints the exception if any accoured.
If this is also intresting for you, I could implement it in the near future.

**Comment by tfarago** [comment]
Good idea, as long as the user can turn it off (sometimes you don't want to see the exception clutter) I would love to see a PR.

**Comment by tfarago** [comment]
Would work for me...

**Comment by MarcusZuber** [comment]
Is anybody aware of a possibility to get a new input-line in ipython?
After a print the cursor is behind the printed string. A '\n' is also only creating a new blank line.

**Comment by MarcusZuber** [comment]
With the python3 asyncio coroutines this is not relevant anymore.
