### ISSUE TITLE
Move write restriction of uca camera properties to libuca

### ISSUE THREAD

**Issue by TimoDritschler** [ufo-kit/concert#361]
We recently added a software-lock to the ```devices.cameras.uca``` implementation which prevents writing camera properties while recording in #354. However, as @tfarago mentioned [here](https://github.com/ufo-kit/concert/pull/354#commitcomment-9522738), this solution is not ideal.

We should make this restriction a bit more flexible and move it to _libuca_ instead, as mentioned in ufo-kit/libuca#63.

**Comment by MariaMatveeva** [comment]
Libuca already has a flexible write restriction, see [here](https://github.com/ufo-kit/libuca/blob/7ff9c59ceb7fd17a5dc7cf3cc3ad39d5c2ed2029/src/uca-camera.c#L1154-L1164) in this commit: https://github.com/ufo-kit/libuca/commit/a389a30e57a038dcfc83dc2814d56a4a1c9a6084.
