### ISSUE TITLE
Mixup of properties when multiple instances of uca-cameras (different uca plugins) are created

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/concert#400]
When instances of different uca-cameras are created it seems, that the newer camera also has properties of the older instances.

`from concert.devices.cameras.uca import Camera`
`cam_a = Camera('mock')`
`cam_b = Camera('file')`
`cam_c = Camera('mock')`

`cam_a` seems to work as expected, `cam_b` has an unimplemented property `degree-value` and `cam_c` has the unimplemented `path` property.

`cam_X.uca.props` shows only the correct properties of each device.

**Comment by matze** [comment]
Hmm, should not happen because we add the camera-specific parameters to the instance not the class but … I will have a look.
