### ISSUE TITLE
Concert is not compatible with the newest version of Pint

### ISSUE THREAD

**Issue by MathiasHurst** [ufo-kit/concert#420]
Concert works with the version 0.5.2 of Pint (as specified in requirements.txt) but for the newest version Pint 0.9 it fails.

**Comment by matze** [comment]
@tfarago are you aware of this?

**Comment by tfarago** [comment]
Yep

**Comment by MarcusZuber** [comment]
Should be "fixed" with this commit https://github.com/ufo-kit/concert/commit/b5533b5e1844b995671668558732e30d2e7a59ca. To get the requirements back to work for newer versions, we have to switch to python3 first.
