### ISSUE TITLE
PyQtGraph Viewer - show cursor coordinates and value in the pixel

### ISSUE THREAD

**Issue by sgasilov** [ufo-kit/concert#465]
Hello, 

The new viewer is very good. Please add option to display the coordinates and intensity under the cursor. 

Thank you,
Sergei.

**Comment by tfarago** [comment]
Hey, glad you like it! To self: just take it from [tofu flow](https://github.com/ufo-kit/tofu/blob/master/tofu/flow/viewer.py#L375)
