### ISSUE TITLE
Experiments: one cannot rely on walker.current

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/concert#472]
Becuase the writer addon uses the experiment's walker, make sure that one is untouched.

**Comment by MarcusZuber** [comment]
Fixed by https://github.com/ufo-kit/concert/pull/473.

The walker should be locked, when the writer is created:

```
async with walker:
        writer = walker.create_writer(producer, name='subdirectory')
```

If `walker.current` needs to read, this hould be also done with a locked writer if it is possible that a `walker.create_writer` can be executed at this time.

**Comment by tfarago** [comment]
You even added a closing documenting statement 👏
