### ISSUE TITLE
skimage.morphology import dilation uses selem which will be deprecated

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/concert#477]
https://github.com/ufo-kit/concert/blob/59e8f2b429988364bcbb31a4bd2585ce362cab02/concert/imageprocessing.py#L228

`from skimage.morphology import dilation` uses selem which will be deprecated:

 FutureWarning: `selem` is a deprecated argument name for `dilation`. It will be removed in version 1.0. Please use `footprint` instead.

**Comment by tfarago** [comment]
I still have 0.18 and footprint is not there.

**Comment by MarcusZuber** [comment]
Fixed in https://github.com/ufo-kit/concert/commit/83a11e07618cd0ff80e549c9a35a416c1ee6388f
